FROM node:16.20.0-alpine
WORKDIR /node-proxy

COPY . /node-proxy

RUN pwd

RUN ls -la

RUN npm install

RUN rm -rf /etc/localtime && ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

EXPOSE 5344
 
ENTRYPOINT ["node", "app.js"]